### ISSUE TITLE
Can't change tab switcher layout

### ISSUE THREAD

**Issue by K1DV5** [kiwibrowser/src.next#169]
No matter what I choose in the tab switcher setting, it's always the old layout.
![Screenshot_20210724-123633](https://user-images.githubusercontent.com/40162008/126864547-0ffb0fde-18e6-402e-ab7d-a0d5b3b3ef4f.jpg)

I'm on Android 10 go and this issue existed in the old version, and on Android 8.1 go.

**Comment by gitdebpro** [comment]
disable simplified tab views  from accessibility and enable tab grid from tab switcher

**Comment by Lartsch** [comment]
Yep, what @gitdebpro is saying. Please close the issue if this solved your problem. @K1DV5

**Comment by K1DV5** [comment]
Tried that, no change☹️

**Comment by Lartsch** [comment]
@K1DV5 You might need to fully close and restart Kiwi. If that doesn't help, clear cache of Kiwi from app settings and try to restart Kiwi again. If that doesn't help, clear Kiwi's data all together from app settings.

**Comment by K1DV5** [comment]
Ok just signed in after doing all of that, and restarting it multiple times, but it's still the same.

**Comment by Lartsch** [comment]
@K1DV5 okay that's weird. no idea then... Maybe it really is related to Android Go but that does not really make sense to me

**Comment by K1DV5** [comment]
Yeah that's what I'm suspecting as well. And I think I remember regular chrome having the same problem on Android 8.1 go. I'll keep this issue in case someone comes up with something.

**Comment by Manu99it** [comment]
guys this happens with apps that request accessibility service for reading screen or press hardware buttons. Try to disable accessibility apps one by one and see wich is the culprit

**Comment by kiwibrowser** [comment]
Absolutely @Manu99it ! In the last version released yesterday (.18) I made that selecting a different tab switcher overrides the accessibility behaviour, so now this should be fixed :)

**Comment by Manu99it** [comment]
> Absolutely @Manu99it ! In the last version released yesterday (.18) I made that selecting a different tab switcher overrides the accessibility behaviour, so now this should be fixed :)

Interesting that you solve a bug Chrome had in years and Google not 😂. Accessibility service in Google is a bit bugged even in other ways, for example button presses from a controller with certain accessibility apps enabled don't works. Google should do something about it ☹️

**Comment by K1DV5** [comment]
Sorry but the problem is still there in the .18 version. I looked into it and [this question](https://stackoverflow.com/questions/68186423/accessibility-service-not-started-on-android-go-edition) is the only clue I found and it doesn't have any answers. So the only possible explanation here, I think, is the fact that it's on android go.

**Comment by Manu99it** [comment]
@K1DV5 did you try to disable every single app that require accessibility settings?

**Comment by kiwibrowser** [comment]
> Sorry but the problem is still there in the .18 version. I looked into it and [this question](https://stackoverflow.com/questions/68186423/accessibility-service-not-started-on-android-go-edition) is the only clue I found and it doesn't have any answers. So the only possible explanation here, I think, is the fact that it's on android go.

Pretty sure the trigger is https://github.com/kiwibrowser/src/blob/ad4fdb6d6e87d5587e4d9b54c6f159ffa055b67d/base/android/java/src/org/chromium/base/SysUtils.java#L114 in this case. I wonder what is the right approach ? Perhaps List by default and let the user override ?

**Comment by Manu99it** [comment]
@kiwibrowser could be a good solution. Maybe with a disclaimer that changing behavior could affect performance

**Comment by K1DV5** [comment]
@Manu99it that's the thing, accessibility shortcut is off in the first place. @kiwibrowser is that function you linked necessary? I mean is there such a big difference if it was removed and all devices were treated the same?

**Comment by d3ward** [comment]
@K1DV5 do you still have the bug with recent builds ? If yes, consider closing the issue

**Comment by K1DV5** [comment]
The bug is still here, so yeah, I think should expect a fix from upstream. Closing.

**Comment by d3ward** [comment]
@K1DV5 as now there are more recent builds with latest chromium from upstream ( we are now on v98 ) , do you have the issue fixed ?

**Comment by K1DV5** [comment]
I'm on v96 (latest on play store) but the problem is still here. I'll notify if it is solved by a later version.

**Comment by d3ward** [comment]
what about now with Kiwi v116 ? I know is been 2 years , but checking 😂

**Comment by K1DV5** [comment]
Haha yeah, long time. I'm on v111, latest from play store, but it's still the same.

**Comment by d3ward** [comment]
Playstore update should be available in couple of days ( depends on Google ) , you can already find the build from sources like apkmirror , otherwise you can have the Github build https://github.com/kiwibrowser/src.next/releases/tag/5616582005 , install DEV to check if fixed

**Comment by K1DV5** [comment]
I got v116 and it finally works! There are some stability issues like inconsistent tabs placement of tabs in the grid layout (bottom and middle) and page content layout breaking (which may be due to memory) and I hope they will be ironed out in the future. Unrelated but the font size seems to respect my choice now. Great work!
