### ISSUE TITLE
The magnifying glass problem still exists.

### ISSUE THREAD

**Issue by drc5521** [kiwibrowser/src.next#375]
**Describe the bug**
The magnifying glass problem still exists.Please watch the video.

**Expected behavior**

URL:https://github.com/kiwibrowser/src.next

**Screenshots**

https://user-images.githubusercontent.com/55195642/132157193-edde9526-4d6c-4c76-bfb7-aedafcec31aa.mp4

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 7]Honor X10
 - Android Version : [e.g. A11 ]A10
 - Kiwi Browser Version [ e.g. 90.0.4577.17 ]Latest version.

**Additional context**

**Comment by d3ward** [comment]
This bug has been fixed in recent builds

**Comment by drc5521** [comment]
> This bug has been fixed in recent builds

oh，no，the problem still exists.

https://user-images.githubusercontent.com/55195642/133967669-ce6c2685-4aad-4f7b-9856-8439b0062402.mp4

**Comment by d3ward** [comment]
Interesting . With top bar works both on mobile and desktop view . While with bottom bar works only on mobile view , bug of magnifier it's still there on desktop mode with bottom bar @kiwibrowser

**Comment by drc5521** [comment]
> Interesting . With top bar works both on mobile and desktop view . While with bottom bar works only on mobile view , bug of magnifier it's still there on desktop mode with bottom bar @kiwibrowser

hi～ 
Perhaps it is caused by this. When the bottom address is swiped to hide, this problem will occur. When it is displayed, the problem disappears.
![Screenshot_20210923_211137](https://user-images.githubusercontent.com/55195642/134513571-5f164a3c-8305-4f83-9fa3-3255b1ca0824.jpg)
![Screenshot_20210923_211234](https://user-images.githubusercontent.com/55195642/134513576-88ea7098-bf52-4832-8947-e6250708aa30.jpg)

**Comment by karl-pae** [comment]
This issue might have been fixed in one of previous build. 

However, I don't see this issue occuring with the latest build linked below, in desktop or mobile mode.

https://github.com/kiwibrowser/src.next/releases/tag/1598596904

**Comment by drc5521** [comment]
> 

When toolbar is hidden, this problem still exists in the latest build.

**Comment by karl-pae** [comment]
Yes. The issue is still there..

I was reproducing one of the issue, later i forgot to turn on hide toolbar.. 😅
