### ISSUE TITLE
No tab strips in tab groups when URL bar at bottom

### ISSUE THREAD

**Issue by nindogo** [kiwibrowser/src.next#401]
When the toolbar is on the bottom the favicons that show the various tabs don't appear when one scrolls. As such the only way to get the tabs in the tab group is to open all tabs.

**Comment by KaKi87** [comment]
I don't understand, but I don't have any issues with favicons display for tabs and tab groups, please post screenshots of your issue.

**Comment by Stvad** [comment]
Any updates on fixing this? had to go back to using the urlbar on top because of this 🙁

**Comment by Practicalbutterfly5** [comment]
Hello, any updates, I also have same issue

**Comment by d3ward** [comment]
I know it's been a while . This is now fixed thanks to improved bottom bar on Kiwi v116. 
( If there are still issues feel free to reopen )

**Comment by Stvad** [comment]
The tab strip bar is still missing if one switches the bar to be at the bottom 🙁

![image](https://github.com/kiwibrowser/src.next/assets/81347/233062e6-cec7-4a16-bb7d-fbd3c054981e)
![image](https://github.com/kiwibrowser/src.next/assets/81347/1598aa16-48c4-4596-8ae8-d7a0fed2f603)

**Comment by Prigoryan** [comment]
@Stvad which version of Kiwi are you running? It's fixed for me on v116.0.5485.22.
Keep in mind that Google Play version is still at v112 and hasn't updated yet.

**Comment by Stvad** [comment]
ah, you’re correct I’m using the playstore version. What is the usual delay between a build appearing here and it getting published?

**Comment by kiwibrowser** [comment]
The Play Store release has started, I have submitted the build to Google (it's the 3rd one, the first 2 were accepted without problems), so it should come in about a week.

If you do not want to wait, you can install this APK on top of your Play Store install:
https://github.com/kiwibrowser/src.next/releases/download/5624320950/com.kiwibrowser.browser-arm64-5624320950-playstore.apk

**Comment by Stvad** [comment]
thank you!
