### ISSUE TITLE
Dark theme doesn't work

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [kiwibrowser/src.next#489]
**Describe the bug**

Dark theme doesn't work.

**To Reproduce**

1. Choose "Dark" in Settings -> Theme or choose "System default" in Settings -> Theme and enable dark theme in Android
2. Open any website that uses `prefers-color-scheme` CSS media query (e.g. https://radek-anuszewski.github.io/prefers-color-scheme-demo/index.html) or just open DevTools

**Expected behavior**

The website or DevTools is displayed in dark theme.

**Current behavior**

The website or DevTools is displayed in light theme.

**Additional context**

This is a regression, this works before. This is a Kiwi Browser bug, not a Chromium bug.

**Comment by kiwibrowser** [comment]
I'm trying to fix it

**Comment by Mav3r1x** [comment]
Go to site settings and turn the dark theme on

**Comment by kiwibrowser** [comment]
Fixed but it requires rebooting the browser as far as I know, to indicate to the renderer that the UI/platform theme has changed

**Comment by FluorescentHallucinogen** [comment]
Just checked the latest version. "System default" in Settings -> Theme still doesn't work at all, only "Dark" works and only after browser reboot.

BTW, in Google Chrome if "System default" is chosed in Settings -> Theme, the theme changes on the fly when user changes theme in Android.

**Comment by kiwibrowser** [comment]
I know :(
I noticed it, it means it's some progress but not right yet.
