### ISSUE TITLE
[BUG] Bottom toolbar empty space on search

### ISSUE THREAD

**Issue by Killerpac** [kiwibrowser/src.next#65]
There is an Empty Space when a Google search is made.![Screenshot_20210721-213858.png](https://user-images.githubusercontent.com/45239423/126522682-0c2069da-c8cb-4e1a-9db1-243792081ec6.png)

**Comment by huazhaozhe** [comment]
There are several bugs with similar situations.

![IMG_20210724_105051](https://user-images.githubusercontent.com/30833807/126855585-15788863-0417-4877-b9ce-59863063f8a1.jpg)

**Comment by d3ward** [comment]
This has been fixed with latest builds

**Comment by kiwibrowser** [comment]
Less frequent in this build but still happening occasionally

**Comment by Killerpac** [comment]
No it's still there For me the latest build didn't do any fix

**Comment by kiwibrowser** [comment]
Yes I reopened it, sorry for the confusion

**Comment by d3ward** [comment]
this issue seems to be fixed 100%
