### ISSUE TITLE
[BUG] External links not working

### ISSUE THREAD

**Issue by Lartsch** [kiwibrowser/src.next#94]
Hey,

I found external links to not open in their respective applications, even when it is enabled from the settings.

As far as I can tell, this applies to all external links (maps, phone, ...) for example when browsing places on Google.

mailto: links seem to work though

// Android 11, OneUI 3.1, default Google apps

**Comment by KaKi87** [comment]
Play Store links work too, can confirm for GMaps & `tel:` links.

**Comment by dagaz** [comment]
I can confirm that magnet-links do not work, too.

Even with chrome://setiings/handlers set to "allow sites..." there works nothing.

**Comment by naifqarni** [comment]
Yeah, reddit links does not open in reddit

**Comment by kiwibrowser** [comment]
Fixed in last build (GitHub only for now) and setting renamed in Accessibility for clarity "prefer native apps"

**Comment by MmyGgithubAaccount** [comment]
Latest github dev arm64 build (Generation 1094043761) on also based android 11 rom

External apps still don't work for me. Also don't have the updated "prefer native apps" text. Was the change reverted?

**Comment by kiwibrowser** [comment]
I think the build system is maybe one build late, let's see with the next one (in +/- 30 mins)

**Comment by MmyGgithubAaccount** [comment]
Generation 1094737737:

Got the updated text but external/native apps still don't work

Also, on this build if I manually select "open in external application" from the long press menu and that doesnt show the [disambiguation dialog](https://developer.android.com/training/basics/intents/sending#disambiguation-dialog) (for example when one of the external apps is set as default to handle that link), then the link doesn't open at all

**Comment by Lartsch** [comment]
Does not work for me either. I'm on OneUI 3.1, maybe that plays a role.

**Comment by Lartsch** [comment]
Works on latest play store version.

**Comment by naifqarni** [comment]
> Works on latest play store version.

Still does not works for me, 
Try opening twitter link or reddit from kiwi and see

**Comment by Lartsch** [comment]
Yep, @naifqarni is right. Some apps still dont work.

**Comment by KaKi87** [comment]
![](https://media.discordapp.net/attachments/494814211579445274/880870814512189460/Screenshot_20210827-204602.jpg)

**Comment by dagaz** [comment]
Thanks for sharing the status information. So now it is also clear why there are no updates in Google Play.

But I consider that a very good reason ;).

**Comment by kiwibrowser** [comment]
The last store update was yesterday actually :D

**Comment by dagaz** [comment]
That's nice and thanks for the information.
It seems that Aurora does not deliver it yet. So - let's sit it out until I have it ;)

**Comment by BartmanEH** [comment]
> Fixed in last build (GitHub only for now) and setting renamed in Accessibility for clarity "prefer native apps"

I've always been boggled as to why this is buried under Accessibility--it really has nothing to do with accessibility. Pretty normal preference to launch a native app to deal with links.

**Comment by KaKi87** [comment]
> Pretty normal preference to launch a native app to deal with links.

Not necessarily for Kiwi users : we use Kiwi because we like our custom experience improved by our settings and extensions, which are mostly not doable in apps.

So, even when I have apps, I prefer manually choosing whether I want to open in app or not.

**Comment by dagaz** [comment]
> Not necessarily for Kiwi users : we use Kiwi because we like our custom experience improved by our settings and extensions, which are mostly not doable in apps.

Hm - Kiwi can not do everything, too. For Example: If it handles a magnet link than it should direct it to an application witch CAN handle the bittorrent protocol. Youtube in Browser is bearable - but Newpipe has a) a download function and b) does not show ads at all. And for me Kiwi is **a browser** and not an email client. So I really do not want to handle "mailto:" itself. There are many reasons why Kiwi users want to use a specialised application for some things.
 
> So, even when I have apps, I prefer manually choosing whether I want to open in app or not.

There I am with you: 3-Button-Menu -> Open in App would be best. And of course working protocol handlers.

**Comment by BartmanEH** [comment]
Instead of waiting for Google Play Store review to enable QUERY_ALL_PACKAGES permission, what about adding a feature in settings to manually assign a specific app for a specific link type? It’s quite tedious right now to long press a link, scan up and down the long list of options to find “copy link address”, copy and it and then paste it in external app. At the very least, a quick method to copy link address would be a good short term solution.

**Comment by BartmanEH** [comment]
any updates on this?

**Comment by kiwibrowser** [comment]
Litterally from Google:
```Thank you so much for your patience. 

Just to update you that our team is still looking into this matter and I apologize for the delay.

I’ll reach out to you the moment we have an update and if you have any further questions in the meantime please let me know, I'm happy to help.
Kind regards,
```

I'll push the 94 series (to not block this release), then I think the browser will be stable enough to wait a little bit for the Google review (and can "afford") to be blocked for a bit

**Comment by BartmanEH** [comment]
OK, thanks. Not sure how I was expected to know that from "Google". Apologies for being annoying. I have been trying to follow the issue in noisy Discord too.

**Comment by kiwibrowser** [comment]
Oh it's not annoying that you ask, it's annoying that Google is so slow to answer. Following your message I have replied back asking for more action.

**Comment by BartmanEH** [comment]
I literally read your quote as an update you had given to the public as opposed to an answer you got from Google (PlayStore). LOL

**Comment by BartmanEH** [comment]
Oh my, how fantastic is that news!

**Comment by d3ward** [comment]
This bus is now fixed with recent [release](https://github.com/kiwibrowser/src.next/releases/tag/1245290316).
An update will also arrive in the store
