### ISSUE TITLE
Grid Tab Switcher jumping around

### ISSUE THREAD

**Issue by afonsojramos** [kiwibrowser/src.next#984]
**Describe the bug**
When closing the last of a row in Grid Tab Switcher *sometimes* it jumps around. Even when I was recording the bug it was happening then it stopped then it started happening again. 

**To Reproduce**
1. Set to Grid Tab Switcher 
2. Open multiple tabs (at least 10 to see the effect) 
3. Close the last row of tabs
4. Voilà

**Expected behavior**
Not jump around. 

**Screenshots**

https://github.com/kiwibrowser/src.next/assets/19473034/f1e41cdd-dfaf-4a04-97b6-4515d3fc3a76

**Smartphone (please complete the following information):**
 - Device: Pixel 7
 - Android Version : A13
 - Kiwi Browser 116.0.5845.72 

**Additional context**

**Comment by blackholeearth** [comment]
Screen Record:
https://youtube.com/watch/I-p3gMTdifY

Somehow i couldn't upload video to github. Used YouTube instead.
----
Also i could not play ur vid.

**Comment by kaoneko** [comment]
For me it already happens with 5 tabs open. **Only when _Bottom toolbar_ is active.** I guess it has to do with the new (and awesome!) functionality that brings the top tiles in reach instead of starting from the top of the screen.

Kiwi Browser 116.0.5845.72, Android 13.

**Comment by rohitghali** [comment]
Can confirm. Happens to me too. As soon as I close 2 tabs, tab switcher just scrolls back to the top.

**Comment by blackholeearth** [comment]
This has been fixed 4 days ago. but introduced new bug.

---------
İn the grid tab mode; When try to scroll up , it suddenly stops and locks. İ have to swipe up 1 or 2 times to break the scroll-freeze.

Then after 1 or 2 row upped it locks and freezes again.

**Comment by jesus2099** [comment]
Still happens in Kiwi Browser 124.0.6327.2
https://github.com/kiwibrowser/android/issues/276
